/* global module */
const DOMAINROBOT_HEADER_DOMAINROBOT_STID = "X-Domainrobot-Stid";

const DOMAINROBOT_HEADER_SESSION_ID = "X-Domainrobot-SessionId";

const DOMAINROBOT_HEADER_PRECEDENCE = "X-Domainrobot-Precedence";

const DOMAINROBOT_HEADER_CONTEXT = "X-Domainrobot-Context";

const DOMAINROBOT_HEADER_BULK_LIMIT = "X-Domainrobot-Bulk-Limit";

const DOMAINROBOT_HEADER_PIN = "X-Domainrobot-Pin";

const DOMAINROBOT_HEADER_2FA_TOKEN = "X-Domainrobot-2FA-Token";

const DOMAINROBOT_HEADER_OWNER_NAME = "X-Domainrobot-Owner-User";

const DOMAINROBOT_HEADER_OWNER_CONTEXT = "X-Domainrobot-Owner-Context";

const DOMAINROBOT_HEADER_DEMO_MODE = "X-Domainrobot-Demo";

const DOMAINROBOT_HEADER_WEBSOCKET = "X-Domainrobot-WS";

const DOMAINROBOT_HEADER_WEBSOCKET_TARGET = "X-Domainrobot-WS-Target";

const DOMAINROBOT_HEADER_CTID = "X-Domainrobot-Ctid";

const DOMAINROBOT_HEADER_SESSION_USER = "X-Domainrobot-Session-User";

const DOMAINROBOT_HEADER_OWNER = "X-Domainrobot-Owner-User";

const DOMAINROBOT_HEADER_CUSTOMER = "X-Domainrobot-Customer";

const DOMAINROBOT_HEADER_PROFILE = "X-Domainrobot-Profile";

const DOMAINROBOT_USER_AGENT = "User-Agent";

const DOMAINROBOT_CONTENT_TYPE = "Content-Type";

module.exports = {
    DOMAINROBOT_HEADER_DOMAINROBOT_STID,
    DOMAINROBOT_HEADER_SESSION_ID,
    DOMAINROBOT_HEADER_PRECEDENCE,
    DOMAINROBOT_HEADER_CONTEXT,
    DOMAINROBOT_HEADER_BULK_LIMIT,
    DOMAINROBOT_HEADER_PIN,
    DOMAINROBOT_HEADER_2FA_TOKEN,
    DOMAINROBOT_HEADER_OWNER_NAME,
    DOMAINROBOT_HEADER_OWNER_CONTEXT,
    DOMAINROBOT_HEADER_DEMO_MODE,
    DOMAINROBOT_HEADER_WEBSOCKET,
    DOMAINROBOT_HEADER_WEBSOCKET_TARGET,
    DOMAINROBOT_HEADER_CTID,
    DOMAINROBOT_HEADER_SESSION_USER,
    DOMAINROBOT_HEADER_OWNER,
    DOMAINROBOT_HEADER_CUSTOMER,
    DOMAINROBOT_HEADER_PROFILE,
    DOMAINROBOT_USER_AGENT,
    DOMAINROBOT_CONTENT_TYPE
};
